// Generated by JFlex 1.9.2 http://jflex.de/  (tweaked for IntelliJ platform)
// source: KarateLexer.flex

package in.srikanthk.devlabs.kchopdebugger.language;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static in.srikanthk.devlabs.kchopdebugger.language.KarateTypes.*;
import com.intellij.psi.TokenType;


public class KarateLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MAIN = 2;
  public static final int WAITING_VALUE = 4;
  public static final int DOC_STRING_BLOCK = 6;
  public static final int SCENARIO = 8;
  public static final int STEP = 10;
  public static final int TABLE = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\1\10\1\0\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\12\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\2\36\1\37\1\40\1\41\7\36\1\42\3\36\1\43"+
    "\1\44\2\36\1\45\3\36\1\46\1\47\1\50\1\51"+
    "\1\36\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\36\1\73\1\74\1\75\1\76\1\77"+
    "\1\36\1\100\2\36\1\101\1\102\1\103\1\104\6\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\3\1\1\3\1\4\1\2\1\5"+
    "\3\3\2\6\1\2\1\3\1\7\1\10\10\3\1\4"+
    "\1\11\1\12\1\1\1\13\1\14\1\15\1\1\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\1\16\35\1\41\1\42\1\43\1\44"+
    "\1\0\2\7\3\0\1\7\1\5\3\3\2\0\11\3"+
    "\1\45\1\46\1\0\1\47\1\0\1\50\3\0\1\51"+
    "\1\52\1\53\1\54\2\0\7\35\1\55\12\35\1\56"+
    "\2\57\2\0\2\3\1\0\1\60\1\61\1\3\1\62"+
    "\5\3\1\26\2\35\1\63\13\35\1\64\2\35\1\65"+
    "\1\0\1\60\2\3\1\66\4\3\1\67\1\70\1\71"+
    "\2\35\1\72\1\35\1\73\2\35\1\74\1\35\1\75"+
    "\2\35\1\76\1\35\1\0\4\3\1\77\1\3\5\35"+
    "\1\100\1\101\1\35\1\102\1\35\1\0\5\3\2\35"+
    "\1\103\1\35\1\104\1\105\1\35\1\0\5\3\4\35"+
    "\1\106\5\3\1\107\1\35\1\110\1\35\1\3\1\0"+
    "\1\111\1\3\1\112\1\0\1\113\1\114\1\115\1\3"+
    "\1\0\1\3\1\0\1\116\1\0\1\117\13\0\1\120"+
    "\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[274];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\105\0\212\0\317\0\u0114\0\u0159\0\u019e\0\u01e3"+
    "\0\u0228\0\u026d\0\u02b2\0\u02f7\0\u019e\0\u033c\0\u0381\0\u03c6"+
    "\0\u040b\0\u0450\0\u019e\0\u0495\0\u04da\0\u051f\0\u0564\0\u02f7"+
    "\0\u05a9\0\u05ee\0\u0633\0\u0678\0\u06bd\0\u0702\0\u0747\0\u078c"+
    "\0\u07d1\0\u0816\0\u085b\0\u08a0\0\u019e\0\u019e\0\u08e5\0\u092a"+
    "\0\u019e\0\u019e\0\u019e\0\u019e\0\u096f\0\u019e\0\u019e\0\u019e"+
    "\0\u09b4\0\u019e\0\u019e\0\u09f9\0\u0a3e\0\u0a83\0\u019e\0\u0ac8"+
    "\0\u019e\0\u019e\0\u019e\0\u0b0d\0\u0b52\0\u0b97\0\u0bdc\0\u0c21"+
    "\0\u0c66\0\u0cab\0\u0cf0\0\u0d35\0\u0d7a\0\u0dbf\0\u0e04\0\u0e49"+
    "\0\u0e8e\0\u0ed3\0\u019e\0\u0f18\0\u019e\0\u019e\0\u0228\0\u019e"+
    "\0\u0f5d\0\u0fa2\0\u0fe7\0\u102c\0\u1071\0\u10b6\0\u10fb\0\u1140"+
    "\0\u1185\0\u0495\0\u11ca\0\u120f\0\u1254\0\u1299\0\u12de\0\u1323"+
    "\0\u1368\0\u13ad\0\u13f2\0\u1437\0\u078c\0\u019e\0\u08a0\0\u019e"+
    "\0\u147c\0\u019e\0\u092a\0\u14c1\0\u1506\0\u019e\0\u019e\0\u019e"+
    "\0\u019e\0\u0b0d\0\u154b\0\u1590\0\u15d5\0\u161a\0\u165f\0\u16a4"+
    "\0\u16e9\0\u172e\0\u0ac8\0\u1773\0\u17b8\0\u17fd\0\u1842\0\u1887"+
    "\0\u18cc\0\u1911\0\u1956\0\u199b\0\u19e0\0\u019e\0\u019e\0\u1a25"+
    "\0\u1a6a\0\u1aaf\0\u1af4\0\u1b39\0\u1b7e\0\u02f7\0\u02f7\0\u1bc3"+
    "\0\u02f7\0\u1c08\0\u1c4d\0\u1c92\0\u1cd7\0\u1d1c\0\u1506\0\u1d61"+
    "\0\u1da6\0\u0ac8\0\u1deb\0\u1e30\0\u1e75\0\u1eba\0\u1eff\0\u1f44"+
    "\0\u1f89\0\u1fce\0\u2013\0\u2058\0\u209d\0\u0ac8\0\u20e2\0\u2127"+
    "\0\u216c\0\u21b1\0\u019e\0\u21f6\0\u223b\0\u019e\0\u2280\0\u22c5"+
    "\0\u230a\0\u234f\0\u02f7\0\u02f7\0\u2394\0\u23d9\0\u241e\0\u0ac8"+
    "\0\u2463\0\u0ac8\0\u24a8\0\u24ed\0\u0ac8\0\u2532\0\u0ac8\0\u2577"+
    "\0\u25bc\0\u0ac8\0\u2601\0\u2646\0\u268b\0\u26d0\0\u2715\0\u275a"+
    "\0\u02f7\0\u279f\0\u27e4\0\u2829\0\u286e\0\u28b3\0\u28f8\0\u0ac8"+
    "\0\u0ac8\0\u293d\0\u0ac8\0\u2982\0\u29c7\0\u2a0c\0\u2a51\0\u2a96"+
    "\0\u2adb\0\u2b20\0\u2b65\0\u2baa\0\u0ac8\0\u2bef\0\u0ac8\0\u0ac8"+
    "\0\u2c34\0\u2c79\0\u2cbe\0\u2d03\0\u2d48\0\u2d8d\0\u2dd2\0\u2e17"+
    "\0\u2e5c\0\u2ea1\0\u2ee6\0\u019e\0\u2f2b\0\u2f70\0\u2fb5\0\u2ffa"+
    "\0\u303f\0\u0ac8\0\u3084\0\u0ac8\0\u30c9\0\u310e\0\u3153\0\u02f7"+
    "\0\u3198\0\u02f7\0\u31dd\0\u02f7\0\u0ac8\0\u0ac8\0\u3222\0\u3267"+
    "\0\u32ac\0\u32f1\0\u02f7\0\u3336\0\u02f7\0\u337b\0\u33c0\0\u3405"+
    "\0\u344a\0\u348f\0\u34d4\0\u3519\0\u355e\0\u35a3\0\u35e8\0\u362d"+
    "\0\u019e\0\u019e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[274];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\7\1\10\1\7\1\10\3\7\1\11\22\7\1\12"+
    "\4\7\1\13\151\7\1\14\1\15\1\16\1\14\1\16"+
    "\1\15\2\14\1\17\22\14\1\20\1\14\1\21\5\14"+
    "\1\22\41\14\2\23\1\24\1\23\1\24\100\23\1\14"+
    "\1\15\1\25\1\14\1\25\1\15\1\14\1\26\1\27"+
    "\5\14\1\30\14\14\1\20\1\31\1\32\1\14\1\33"+
    "\1\14\1\34\1\14\1\35\1\36\1\37\34\14\1\40"+
    "\2\14\1\7\1\41\1\42\1\7\1\42\1\41\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\7\12\70\1\71\1\7"+
    "\1\72\1\73\1\74\2\70\1\75\1\76\1\77\1\100"+
    "\2\70\1\101\1\102\1\103\1\70\1\104\1\105\1\70"+
    "\1\106\1\107\1\110\1\111\2\70\1\112\1\113\1\114"+
    "\1\115\1\116\107\0\1\10\1\0\1\10\100\0\2\117"+
    "\1\120\1\117\1\121\100\117\2\122\1\0\1\122\1\0"+
    "\100\122\57\0\1\123\25\0\1\14\2\0\1\14\2\0"+
    "\77\14\1\0\2\16\1\0\2\16\1\0\1\124\1\125"+
    "\74\0\1\17\1\126\1\0\1\14\1\0\1\126\77\17"+
    "\1\127\1\122\1\0\1\127\1\0\1\122\77\127\1\14"+
    "\2\0\1\14\2\0\45\14\1\130\32\14\2\0\1\14"+
    "\2\0\47\14\1\131\27\14\1\0\2\132\1\0\2\132"+
    "\1\0\1\133\76\0\2\25\1\0\2\25\2\0\1\125"+
    "\74\0\1\14\2\0\1\14\2\0\1\14\1\134\75\14"+
    "\1\27\1\125\1\0\1\14\1\0\1\125\77\27\1\14"+
    "\2\0\1\14\2\0\62\14\1\135\15\14\2\0\1\14"+
    "\2\0\45\14\1\136\22\14\1\137\7\14\2\0\1\14"+
    "\2\0\72\14\1\140\5\14\2\0\1\14\2\0\55\14"+
    "\1\141\22\14\2\0\1\14\2\0\47\14\1\142\30\14"+
    "\2\0\1\14\2\0\54\14\1\143\23\14\2\0\1\14"+
    "\2\0\54\14\1\144\22\14\2\145\1\0\1\145\1\0"+
    "\100\145\1\0\1\41\3\0\1\41\12\0\1\55\65\0"+
    "\2\42\1\0\2\42\127\0\1\146\54\0\2\147\1\0"+
    "\1\147\1\0\2\147\1\150\37\147\1\151\35\147\12\0"+
    "\1\152\72\0\2\153\1\0\1\153\1\0\6\153\1\150"+
    "\33\153\1\154\35\153\1\0\1\55\3\0\1\55\121\0"+
    "\1\155\1\0\1\61\110\0\1\156\104\0\1\157\1\160"+
    "\103\0\1\161\100\0\1\70\7\0\12\70\5\0\26\70"+
    "\4\0\2\162\1\0\1\162\1\0\42\162\1\163\2\162"+
    "\1\150\32\162\24\0\1\70\7\0\12\70\5\0\1\164"+
    "\15\70\1\165\7\70\30\0\1\70\7\0\12\70\5\0"+
    "\4\70\1\166\13\70\1\167\5\70\30\0\1\70\7\0"+
    "\12\70\5\0\13\70\1\170\12\70\30\0\1\70\7\0"+
    "\12\70\5\0\1\171\22\70\1\172\2\70\30\0\1\70"+
    "\7\0\12\70\5\0\5\70\1\173\20\70\30\0\1\70"+
    "\7\0\12\70\5\0\21\70\1\174\4\70\30\0\1\70"+
    "\7\0\12\70\5\0\1\175\25\70\30\0\1\70\7\0"+
    "\12\70\5\0\1\176\25\70\30\0\1\70\7\0\12\70"+
    "\5\0\23\70\1\177\2\70\30\0\1\70\7\0\12\70"+
    "\5\0\20\70\1\200\5\70\30\0\1\70\7\0\12\70"+
    "\5\0\4\70\1\201\21\70\30\0\1\70\7\0\12\70"+
    "\5\0\4\70\1\202\21\70\30\0\1\70\7\0\12\70"+
    "\5\0\1\203\17\70\1\204\5\70\30\0\1\70\7\0"+
    "\12\70\5\0\14\70\1\205\11\70\106\0\1\206\4\0"+
    "\1\120\102\0\2\122\1\207\1\122\1\210\100\122\53\0"+
    "\1\211\40\0\1\212\75\0\2\125\3\0\100\125\2\126"+
    "\3\0\100\126\1\127\1\122\1\207\1\127\1\210\1\122"+
    "\77\127\1\14\2\0\1\14\2\0\47\14\1\213\30\14"+
    "\2\0\1\14\2\0\51\14\1\214\25\14\7\0\1\215"+
    "\75\0\1\14\2\0\1\14\2\0\1\14\1\216\76\14"+
    "\2\0\1\14\2\0\50\14\1\217\27\14\2\0\1\14"+
    "\2\0\47\14\1\220\30\14\2\0\1\14\2\0\67\14"+
    "\1\221\10\14\2\0\1\14\2\0\45\14\1\222\32\14"+
    "\2\0\1\14\2\0\71\14\1\223\6\14\2\0\1\14"+
    "\2\0\51\14\1\224\26\14\2\0\1\14\2\0\51\14"+
    "\1\225\26\14\2\0\1\14\2\0\51\14\1\226\25\14"+
    "\2\147\3\0\100\147\2\153\3\0\100\153\24\0\1\227"+
    "\60\0\2\162\3\0\100\162\24\0\1\70\7\0\12\70"+
    "\5\0\13\70\1\230\12\70\30\0\1\70\7\0\12\70"+
    "\5\0\15\70\1\231\10\70\30\0\1\70\7\0\12\70"+
    "\5\0\5\70\1\232\20\70\30\0\1\70\7\0\12\70"+
    "\5\0\10\70\1\233\15\70\30\0\1\70\7\0\12\70"+
    "\5\0\21\70\1\234\4\70\30\0\1\70\7\0\12\70"+
    "\5\0\13\70\1\235\12\70\30\0\1\70\7\0\12\70"+
    "\5\0\15\70\1\236\10\70\30\0\1\70\7\0\12\70"+
    "\5\0\16\70\1\237\7\70\30\0\1\70\7\0\12\70"+
    "\5\0\20\70\1\240\5\70\30\0\1\70\7\0\12\70"+
    "\5\0\22\70\1\241\3\70\30\0\1\70\7\0\12\70"+
    "\5\0\13\70\1\242\12\70\30\0\1\70\7\0\12\70"+
    "\5\0\10\70\1\243\15\70\30\0\1\70\7\0\12\70"+
    "\5\0\1\244\21\70\1\245\3\70\30\0\1\70\7\0"+
    "\12\70\5\0\22\70\1\246\3\70\30\0\1\70\7\0"+
    "\12\70\5\0\1\70\1\247\24\70\30\0\1\70\7\0"+
    "\12\70\5\0\23\70\1\250\2\70\30\0\1\70\7\0"+
    "\12\70\5\0\13\70\1\251\12\70\6\0\1\207\177\0"+
    "\1\252\16\0\1\253\75\0\1\14\2\0\1\14\2\0"+
    "\57\14\1\254\20\14\2\0\1\14\2\0\62\14\1\255"+
    "\14\14\7\0\1\256\75\0\1\14\2\0\1\14\2\0"+
    "\57\14\1\257\20\14\2\0\1\14\2\0\61\14\1\260"+
    "\16\14\2\0\1\14\2\0\51\14\1\261\26\14\2\0"+
    "\1\14\2\0\62\14\1\262\15\14\2\0\1\14\2\0"+
    "\62\14\1\263\15\14\2\0\1\14\2\0\62\14\1\264"+
    "\14\14\24\0\1\70\7\0\12\70\5\0\13\70\1\265"+
    "\12\70\30\0\1\70\7\0\12\70\5\0\5\70\1\266"+
    "\20\70\30\0\1\70\7\0\12\70\5\0\24\70\1\267"+
    "\1\70\30\0\1\70\7\0\12\70\5\0\4\70\1\270"+
    "\21\70\30\0\1\70\7\0\12\70\5\0\21\70\1\250"+
    "\4\70\30\0\1\70\7\0\12\70\5\0\2\70\1\271"+
    "\23\70\30\0\1\70\7\0\12\70\5\0\15\70\1\272"+
    "\10\70\30\0\1\70\7\0\12\70\5\0\1\273\25\70"+
    "\30\0\1\70\7\0\12\70\5\0\2\70\1\274\23\70"+
    "\30\0\1\70\7\0\12\70\5\0\13\70\1\275\12\70"+
    "\30\0\1\70\7\0\12\70\5\0\15\70\1\276\10\70"+
    "\30\0\1\70\7\0\12\70\5\0\3\70\1\277\22\70"+
    "\30\0\1\70\7\0\12\70\5\0\23\70\1\300\2\70"+
    "\30\0\1\70\7\0\12\70\5\0\13\70\1\301\12\70"+
    "\30\0\1\70\7\0\12\70\5\0\4\70\1\302\21\70"+
    "\30\0\1\70\7\0\12\70\5\0\21\70\1\303\4\70"+
    "\102\0\1\304\6\0\1\14\2\0\1\14\2\0\53\14"+
    "\1\305\24\14\2\0\1\14\2\0\45\14\1\306\32\14"+
    "\2\0\1\14\2\0\53\14\1\307\24\14\2\0\1\14"+
    "\2\0\64\14\1\310\13\14\2\0\1\14\2\0\62\14"+
    "\1\311\15\14\2\0\1\14\2\0\45\14\1\312\31\14"+
    "\24\0\1\70\7\0\12\70\5\0\16\70\1\313\7\70"+
    "\30\0\1\70\7\0\12\70\5\0\10\70\1\314\15\70"+
    "\30\0\1\70\7\0\12\70\5\0\4\70\1\315\21\70"+
    "\30\0\1\70\7\0\12\70\5\0\22\70\1\316\3\70"+
    "\30\0\1\70\7\0\12\70\5\0\22\70\1\317\3\70"+
    "\30\0\1\70\7\0\12\70\5\0\7\70\1\320\16\70"+
    "\30\0\1\70\7\0\12\70\5\0\22\70\1\321\3\70"+
    "\30\0\1\70\7\0\12\70\5\0\20\70\1\322\5\70"+
    "\30\0\1\70\7\0\12\70\5\0\4\70\1\323\21\70"+
    "\30\0\1\70\7\0\12\70\5\0\22\70\1\324\3\70"+
    "\77\0\1\325\11\0\1\14\2\0\1\14\2\0\65\14"+
    "\1\326\12\14\2\0\1\14\2\0\65\14\1\327\12\14"+
    "\2\0\1\14\2\0\65\14\1\330\12\14\2\0\1\14"+
    "\2\0\60\14\1\331\17\14\2\0\1\14\2\0\65\14"+
    "\1\332\11\14\24\0\1\70\7\0\12\70\5\0\15\70"+
    "\1\333\10\70\30\0\1\70\7\0\12\70\5\0\6\70"+
    "\1\334\17\70\30\0\1\70\7\0\12\70\5\0\20\70"+
    "\1\335\5\70\30\0\1\70\7\0\12\70\5\0\10\70"+
    "\1\336\15\70\30\0\1\70\7\0\12\70\5\0\4\70"+
    "\1\337\21\70\30\0\1\70\7\0\12\70\5\0\15\70"+
    "\1\340\10\70\30\0\1\70\7\0\12\70\5\0\20\70"+
    "\1\341\5\70\63\0\1\342\25\0\1\14\2\0\1\14"+
    "\2\0\63\14\1\343\14\14\2\0\1\14\2\0\55\14"+
    "\1\344\22\14\2\0\1\14\2\0\63\14\1\345\14\14"+
    "\2\0\1\14\2\0\51\14\1\346\26\14\2\0\1\14"+
    "\2\0\55\14\1\347\21\14\24\0\1\70\7\0\12\70"+
    "\5\0\2\70\1\350\23\70\30\0\1\70\7\0\12\70"+
    "\5\0\23\70\1\351\2\70\30\0\1\70\7\0\12\70"+
    "\5\0\16\70\1\352\7\70\30\0\1\70\7\0\12\70"+
    "\5\0\10\70\1\353\15\70\31\0\1\354\57\0\1\14"+
    "\2\0\1\14\2\0\70\14\1\355\7\14\2\0\1\14"+
    "\2\0\63\14\1\356\14\14\2\0\1\14\2\0\70\14"+
    "\1\357\7\14\2\0\1\14\2\0\66\14\1\360\11\14"+
    "\2\0\1\14\2\0\63\14\1\361\13\14\24\0\1\70"+
    "\7\0\12\70\5\0\4\70\1\362\21\70\30\0\1\70"+
    "\7\0\12\70\5\0\20\70\1\363\5\70\30\0\1\70"+
    "\7\0\12\70\5\0\15\70\1\364\10\70\30\0\1\70"+
    "\7\0\12\70\5\0\15\70\1\365\10\70\4\0\1\14"+
    "\2\0\1\14\2\0\62\14\1\366\15\14\2\0\1\14"+
    "\1\0\1\367\17\14\1\370\60\14\2\0\1\14\2\0"+
    "\62\14\1\371\15\14\2\0\1\14\2\0\17\14\1\372"+
    "\60\14\2\0\1\14\1\0\1\373\17\14\1\374\57\14"+
    "\24\0\1\70\7\0\12\70\5\0\4\70\1\375\21\70"+
    "\30\0\1\70\7\0\12\70\5\0\6\70\1\376\17\70"+
    "\4\0\1\14\2\0\1\14\2\0\50\14\1\377\26\14"+
    "\42\0\1\u0100\42\0\1\14\2\0\1\14\2\0\50\14"+
    "\1\u0101\26\14\42\0\1\u0102\42\0\1\14\2\0\1\14"+
    "\2\0\17\14\1\u0103\57\14\76\0\1\u0104\6\0\1\14"+
    "\2\0\1\14\2\0\17\14\1\u0105\57\14\76\0\1\u0106"+
    "\103\0\1\u0107\104\0\1\u0108\75\0\1\u0109\104\0\1\u010a"+
    "\101\0\1\u010b\104\0\1\u010c\111\0\1\u010d\104\0\1\u010e"+
    "\73\0\1\u010f\104\0\1\u0110\52\0\1\u0111\104\0\1\u0112"+
    "\57\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[13938];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\11\5\1\1\11\5\1\1\11\21\1\2\11"+
    "\2\1\4\11\1\1\3\11\1\1\2\11\3\1\1\11"+
    "\1\1\3\11\17\1\1\11\1\1\2\11\1\0\1\11"+
    "\1\1\3\0\5\1\2\0\12\1\1\11\1\0\1\11"+
    "\1\0\1\11\3\0\4\11\2\0\22\1\2\11\1\1"+
    "\2\0\2\1\1\0\34\1\1\0\1\11\2\1\1\11"+
    "\25\1\1\0\20\1\1\0\14\1\1\0\11\1\1\11"+
    "\12\1\1\0\3\1\1\0\4\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\13\0\2\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[274];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private StringBuilder stringBuffer = new StringBuilder();
    public KarateLexer() {
      this((java.io.Reader) null);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public KarateLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return TokenType.BAD_CHARACTER;
            }
          // fall through
          case 82: break;
          case 2:
            { return NEWLINE;
            }
          // fall through
          case 83: break;
          case 3:
            { return WORD_KEY;
            }
          // fall through
          case 84: break;
          case 4:
            { return WS_KEY;
            }
          // fall through
          case 85: break;
          case 5:
            { /* ignore comment */
            }
          // fall through
          case 86: break;
          case 6:
            { return DOC_STRING_CONTENT;
            }
          // fall through
          case 87: break;
          case 7:
            { return COMMENT_STMT;
            }
          // fall through
          case 88: break;
          case 8:
            { yybegin(STEP); return STAR_STEP;
            }
          // fall through
          case 89: break;
          case 9:
            { yybegin(SCENARIO); return NEWLINE;
            }
          // fall through
          case 90: break;
          case 10:
            { return BANG_OPERATOR;
            }
          // fall through
          case 91: break;
          case 11:
            { return OCTOTHORPE;
            }
          // fall through
          case 92: break;
          case 12:
            { return MODULO_OPERATOR;
            }
          // fall through
          case 93: break;
          case 13:
            { return AMPERSAND_OPERATOR;
            }
          // fall through
          case 94: break;
          case 14:
            { return L_PAREN;
            }
          // fall through
          case 95: break;
          case 15:
            { return R_PAREN;
            }
          // fall through
          case 96: break;
          case 16:
            { return MULTIPLY_OPERATOR;
            }
          // fall through
          case 97: break;
          case 17:
            { return PLUS_OPERATOR;
            }
          // fall through
          case 98: break;
          case 18:
            { return COMMA;
            }
          // fall through
          case 99: break;
          case 19:
            { return MINUS_OPERATOR;
            }
          // fall through
          case 100: break;
          case 20:
            { return DOT_OPERATOR;
            }
          // fall through
          case 101: break;
          case 21:
            { return DIVIDE_OPERATOR;
            }
          // fall through
          case 102: break;
          case 22:
            { return NUMBER_LITERAL;
            }
          // fall through
          case 103: break;
          case 23:
            { return COLON_OPERATOR;
            }
          // fall through
          case 104: break;
          case 24:
            { return SEMICOLON;
            }
          // fall through
          case 105: break;
          case 25:
            { return LESS_THAN_OPERATOR;
            }
          // fall through
          case 106: break;
          case 26:
            { return ASSIGNMENT_OPERATOR;
            }
          // fall through
          case 107: break;
          case 27:
            { return GREATER_THAN_OPERATOR;
            }
          // fall through
          case 108: break;
          case 28:
            { return TERNARY_OPERATOR;
            }
          // fall through
          case 109: break;
          case 29:
            { return IDENTIFIER_KEYWORD;
            }
          // fall through
          case 110: break;
          case 30:
            { return L_SQUARE;
            }
          // fall through
          case 111: break;
          case 31:
            { return R_SQUARE;
            }
          // fall through
          case 112: break;
          case 32:
            { return LOGICAL_XOR_OPERATOR;
            }
          // fall through
          case 113: break;
          case 33:
            { return L_CURLY;
            }
          // fall through
          case 114: break;
          case 34:
            { return PIPE_OPERATOR;
            }
          // fall through
          case 115: break;
          case 35:
            { return R_CURLY;
            }
          // fall through
          case 116: break;
          case 36:
            { return TILDE_OPERATOR;
            }
          // fall through
          case 117: break;
          case 37:
            { return TABLE_ROW;
            }
          // fall through
          case 118: break;
          case 38:
            { return NOT_EQUALS_OPERATOR;
            }
          // fall through
          case 119: break;
          case 39:
            { return STRING_LITERAL;
            }
          // fall through
          case 120: break;
          case 40:
            { return LOGICAL_AND_OPERATOR;
            }
          // fall through
          case 121: break;
          case 41:
            { return LESS_THAN_EQUAL_OPERATOR;
            }
          // fall through
          case 122: break;
          case 42:
            { return EQUALS_OPERATOR;
            }
          // fall through
          case 123: break;
          case 43:
            { return ARROW_OPERATOR;
            }
          // fall through
          case 124: break;
          case 44:
            { return GREATER_THAN_EQUAL_OPERATOR;
            }
          // fall through
          case 125: break;
          case 45:
            { return IF_KEYWORD;
            }
          // fall through
          case 126: break;
          case 46:
            { return LOGICAL_OR_OPERATOR;
            }
          // fall through
          case 127: break;
          case 47:
            { return TAGS_KEY;
            }
          // fall through
          case 128: break;
          case 48:
            { yybegin(DOC_STRING_BLOCK); return DOC_STRING_START;
            }
          // fall through
          case 129: break;
          case 49:
            { yybegin(STEP); return AND_STEP;
            }
          // fall through
          case 130: break;
          case 50:
            { yybegin(STEP); return BUT_STEP;
            }
          // fall through
          case 131: break;
          case 51:
            { return DEF_KEYWORD;
            }
          // fall through
          case 132: break;
          case 52:
            { return SET_KEYWORD;
            }
          // fall through
          case 133: break;
          case 53:
            { return XML_KEYWORD;
            }
          // fall through
          case 134: break;
          case 54:
            { yybegin(SCENARIO);
                  return DOC_STRING_END;
            }
          // fall through
          case 135: break;
          case 55:
            { yybegin(STEP); return THEN_STEP;
            }
          // fall through
          case 136: break;
          case 56:
            { yybegin(STEP); return WHEN_STEP;
            }
          // fall through
          case 137: break;
          case 57:
            { return CALL_KEYWORD;
            }
          // fall through
          case 138: break;
          case 58:
            { return ELSE_KEYWORD;
            }
          // fall through
          case 139: break;
          case 59:
            { return JSON_KEYWORD;
            }
          // fall through
          case 140: break;
          case 60:
            { return NULL_LITERAL;
            }
          // fall through
          case 141: break;
          case 61:
            { return READ_KEYWORD;
            }
          // fall through
          case 142: break;
          case 62:
            { return BOOLEAN_LITERAL;
            }
          // fall through
          case 143: break;
          case 63:
            { yybegin(STEP); return GIVEN_STEP;
            }
          // fall through
          case 144: break;
          case 64:
            { return MATCH_KEYWORD;
            }
          // fall through
          case 145: break;
          case 65:
            { return PRINT_KEYWORD;
            }
          // fall through
          case 146: break;
          case 66:
            { return TABLE_KEYWORD;
            }
          // fall through
          case 147: break;
          case 67:
            { return DRIVER_KEYWORD;
            }
          // fall through
          case 148: break;
          case 68:
            { return KARATE_KEYWORD;
            }
          // fall through
          case 149: break;
          case 69:
            { return RETURN_KEYWORD;
            }
          // fall through
          case 150: break;
          case 70:
            { yybegin(WAITING_VALUE); return FEATURE_KEYWORD;
            }
          // fall through
          case 151: break;
          case 71:
            { return CALLONCE_KEYWORD;
            }
          // fall through
          case 152: break;
          case 72:
            { return FUNCTION_KEYWORD;
            }
          // fall through
          case 153: break;
          case 73:
            { yybegin(SCENARIO); return SCENARIO_KEYWORD;
            }
          // fall through
          case 154: break;
          case 74:
            { return EXAMPLES_KEYWORD;
            }
          // fall through
          case 155: break;
          case 75:
            { return SCENARIO_KEYWORD;
            }
          // fall through
          case 156: break;
          case 76:
            { return CONFIGURE_KEYWORD;
            }
          // fall through
          case 157: break;
          case 77:
            { return XMLSTRING_KEYWORD;
            }
          // fall through
          case 158: break;
          case 78:
            { yybegin(SCENARIO); return BACKGROUND_KEYWORD;
            }
          // fall through
          case 159: break;
          case 79:
            { return BACKGROUND_KEYWORD;
            }
          // fall through
          case 160: break;
          case 80:
            { yybegin(SCENARIO); return SCENARIO_OUTLINE_KEYWORD;
            }
          // fall through
          case 161: break;
          case 81:
            { return SCENARIO_OUTLINE_KEYWORD;
            }
          // fall through
          case 162: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
