{
  parserClass = "in.srikanthk.devlabs.kchopdebugger.language.KarateParser";
  extends = "com.intellij.extapi.psi.ASTWrapperPsiElement";

  psiClassPrefix = "Karate";
  psiImplClassSuffix = "Impl";
  psiPackage = "in.srikanthk.devlabs.kchopdebugger.language.psi";
  psiImplPackage = "in.srikanthk.devlabs.kchopdebugger.language.psi.impl";

  elementTypeHolderClass = "in.srikanthk.devlabs.kchopdebugger.language.KarateTypes";
  elementTypeClass = "in.srikanthk.devlabs.kchopdebugger.language.KarateElementType";
  tokenTypeClass = "in.srikanthk.devlabs.kchopdebugger.language.KarateTokenType";
}

feature ::= tags? FEATURE_KEYWORD feature_description? background? (scenario | scenario_outline)* NEWLINE*

feature_description ::= line+

line ::= NEWLINE? TEXT+

comment ::= COMMENT_STMT NEWLINE

tags ::= NEWLINE? TAGS_KEY+

background ::= tags? BACKGROUND_KEYWORD TEXT* (step | doc_string | table)*

step ::= (STAR_STEP | GIVEN_STEP | WHEN_STEP | THEN_STEP | AND_STEP | BUT_STEP) TEXT*

scenario ::= tags? SCENARIO_KEYWORD TEXT* (step | doc_string | table)*

scenario_outline ::= tags? SCENARIO_OUTLINE_KEYWORD TEXT* (step | doc_string | table)* examples

examples ::= EXAMPLES_KEYWORD table*

table    ::= NEWLINE? TABLE_ROW+

doc_string ::= DOC_STRING_KEY TEXT* DOC_STRING_KEY